/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package util;

import Formularios.NOVO_LOGIN;
import static groovy.xml.Entity.quot;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static nickyb.sqleonardo.environment.Application.session;
import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.Email;
import org.apache.commons.mail.EmailAttachment;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.HtmlEmail;
import org.apache.commons.mail.MultiPartEmail;
import org.apache.commons.mail.SimpleEmail;
import org.jdesktop.swingx.treetable.AbstractTreeTableModel;

public class TESTE_EMAIL extends javax.swing.JFrame {

    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy " + "| " + "HH:mm");
    DateTimeFormatter dia_hora = DateTimeFormatter.ofPattern("HH:mm");
    DateTimeFormatter segundo = DateTimeFormatter.ofPattern("ss");
    DateTimeFormatter dataReferencia1 = DateTimeFormatter.ofPattern("yyyyMMdd");

    String dataDigiatacao = dtf.format(LocalDateTime.now());
    String dataAtual = dia_hora.format(LocalDateTime.now());
    String segundoAtual = segundo.format(LocalDateTime.now());
    String dataReferencia = dataReferencia1.format(LocalDateTime.now());

    public TESTE_EMAIL() {
        initComponents();

    }

    public void enviarEmail() {

        try {
            String meuEmail = "notificacao@aguitech.com.br";
            String senha = "C@rlim051215";

            String memsagem;
            memsagem = "<html>Codigo do produto: <b>120100003</b></html>";

            Email email = new SimpleEmail();
            email.setHostName("email-ssl.com.br");
            email.setSmtpPort(465);
            email.setAuthentication(meuEmail, senha);
            email.setSSLOnConnect(true);
            email.setTLS(true);
            email.setFrom(meuEmail);
            email.setSubject("Cadastro de Produto");
            email.setMsg("<html>apenas esta parte em <b>negrito</b></html>");
            email.addTo("edicarlos@agrfamosa.com.br");
            email.send();

            //     JOptionPane.showMessageDialog(this, "E-mail enviado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao enviar e-mail " + e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24x24/E-mail.png"))); // NOI18N
        jButton1.setText("Enviar e-mail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblHora.setBackground(new java.awt.Color(255, 255, 255));
        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora");
        lblHora.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String meuEmail = "notificacao@aguitech.com.br";
        String senha = "C@rlim051215";

        HtmlEmail email = new HtmlEmail();
        email.setSSLOnConnect(true);
        email.setHostName("email-ssl.com.br");
        email.setSslSmtpPort("465");
        email.setAuthentication(meuEmail, senha);
        try {
            email.setFrom(meuEmail, "AGUITECH");
            email.setDebug(true);
            email.setSubject("Assunto do E-mail");

            StringBuilder builder = new StringBuilder();
            builder.append("<h1>Um titulo</h1>");
            builder.append("<p>Lorem ipsum dolor sit amet, <b>consectetur adipiscing elit</b>. Duis nec aliquam tortor. Sed dignissim dolor ac est consequat egestas. Praesent adipiscing dolor in consectetur fringilla.</p>");
            //  builder.append("<a href=\"http://wwww.botecodigital.info\">Boteco Digital</a> <br> ");
            //   builder.append("<img src=\"http://www.botecodigital.info/wp-content/themes/boteco/img/logo.png\">");

            int cont = 1;
            while (10 > cont) {

                String nome = "Edicalros";
                int idade = 22;
                String profissao = "Administrador";

                builder.append(" <table border=\"1\">\n"
                        + "        <tr>\n"
                        + "            <td>" + nome + "" + cont + "</td>\n"
                        + "            <td>" + idade + "" + cont + "</td>\n"
                        + "            <td>" + profissao + "" + cont + "</td>\n"
                        + "        </tr>"
                        + "    </table>");
                cont++;
            }

            email.setHtmlMsg(builder.toString());
            email.addTo("edicarlosaguiar14@gmail.com");
            email.send();
        } catch (EmailException e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(this, "E-mail enviado com sucesso!");

        /*   } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao enviar e-mail " + e);

        }*/

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Date ds = new Date();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
        String h = dtf.format(LocalTime.now());

        Timer time = new Timer(10, new hora());
        time.start();


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TESTE_EMAIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TESTE_EMAIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TESTE_EMAIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TESTE_EMAIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TESTE_EMAIL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblHora;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
        DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("dd-MM-yyyy");

        String dia = dtf2.format(LocalDateTime.now());
        String hora = dtf.format(LocalDateTime.now());

        @Override
        public void actionPerformed(ActionEvent e) {

            Calendar now = Calendar.getInstance();
            lblHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
//           lblHora.setText(String.format(dia + " | " + "%1$tH:%1$tM:%1$tS", now));
            if (lblHora.getText().equals("14:36:00")) {
                enviarEmail();
            } else {

            }

        }

    }

}
