/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import ARRAY_STATIC.ArrayProdutos;
import Model.ModelOperacaoCaixaPDV;
import Model.ModelUsuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.Utilities;
import util.AguardeGerandoRelatorio;
import util.Conexao;
import util.utilitario;

/**
 *
 * @author Edicarlos
 */
public class JF_MENU extends javax.swing.JFrame {

    utilitario util = new utilitario();
    String nivelUser;

    Conexao conn = new Conexao();
    ArrayProdutos prod = new ArrayProdutos();

    BASE_PROD produto = new BASE_PROD();

    public JF_MENU() {
        initComponents();
        centerWindow(this);
        lblServidor.setText("Servidor Logado | " + conn.getServidor() + " ");
        this.setTitle(util.getTituloPrincipal());
        utilitario util = new utilitario();
        util.inserirIcon(this);
        this.setExtendedState(MAXIMIZED_BOTH);
        ModelUsuario user = new ModelUsuario();

        if (user.getNivelUsuario() >= 11) {
            nivelUser = "Administrador";
        } else {
            nivelUser = "Usuario Comum - Com restrinções aplicadas";
        }

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy" + " - " + "HH:mm:ss");
        lblDatahora.setText(" " + user.getUsuarioLogado() + " - " + nivelUser + " | " + util.getDataBase()+" | "+"Ult. Fech: "+
                util.getUltimoFechamento());

        menuPermissoes.setEnabled(false);

        subMPC.setEnabled(false);
        subMSC.setEnabled(false);
        lblDadosEmpresa.setText(util.getDadosEmpresaRodape());
        verificaNivelUsuario();

    }

    public void verificaNivelUsuario() {
        ModelUsuario user = new ModelUsuario();

        //REstrimões oa modulo Estoque/Custos
        if (user.getUsuarioLogado().equals("Tiago")) {
            btnPlantio.setEnabled(false);
            btnRequisicao.setEnabled(false);
            jMenuMovimentacao.setEnabled(false);
            btnProducao.setEnabled(false);
            btnProduto.setEnabled(false);
            JItemMenu_Prod.setEnabled(false);
            JItemMenu_Cat.setEnabled(false);
            JItemMenu_Sub.setEnabled(false);

            //Restrições ao modulo financeiro
        } else if (user.getUsuarioLogado().equals("Edicarlos1")) {
            btnContaPagar.setEnabled(false);
            btnContaReceber.setEnabled(false);
            btnvenda.setEnabled(false);
            btnCompra.setEnabled(false);
            menuCompra.setEnabled(false);
            menuVenda.setEnabled(false);
            menuFinanceiro.setEnabled(false);
            JmRH.setEnabled(false);

        } else {

        }
    }

    public void configuracaoInicial() {
        btnProduto.setOpaque(true);
        btnProduto.setBackground(Color.WHITE);
    }

    public void abrirCaixa() {
        Caixa_PDV cx = new Caixa_PDV(this, true);
        cx.setVisible(true);
    }

    public void ataulizarBrowses() {

        produto.carregaArray();
        produto.carregaTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        painelDeTrabalho = new javax.swing.JDesktopPane(){

        };
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        lblDatahora = new javax.swing.JLabel();
        lblDadosEmpresa = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        lblServidor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnProduto = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnvenda = new javax.swing.JButton();
        btnContaPagar = new javax.swing.JButton();
        btnContaReceber = new javax.swing.JButton();
        btnPlantio = new javax.swing.JButton();
        btnRequisicao = new javax.swing.JButton();
        btnProducao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JItemMenu_Prod = new javax.swing.JMenuItem();
        JItemMenu_Cat = new javax.swing.JMenuItem();
        JItemMenu_Sub = new javax.swing.JMenuItem();
        JItemMenu_Forn = new javax.swing.JMenuItem();
        JItemMenu_Cli = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenu();
        subMCompra = new javax.swing.JMenuItem();
        subMSC = new javax.swing.JMenuItem();
        subMPC = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        itemMenuBancos = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        JmRH = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuMovimentacao = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        JmEstoque = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuNovoUsuario = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        menuPermissoes = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();

        jMenuItem27.setText("jMenuItem27");

        jMenu10.setText("File");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar2.add(jMenu11);

        jMenuItem44.setText("jMenuItem44");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        painelDeTrabalho.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        kGradientPanel2.setBackground(new java.awt.Color(0, 51, 51));
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel2.setkGradientFocus(1500);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));

        lblDatahora.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblDatahora.setForeground(new java.awt.Color(51, 51, 51));
        lblDatahora.setText("Data e Hora:");

        lblDadosEmpresa.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblDadosEmpresa.setForeground(new java.awt.Color(51, 51, 51));
        lblDadosEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDadosEmpresa.setText(" Direitos de uso temporário cedido à: BIG JOY BRINQUEDOS | Modulo: TESTE");

        btnReiniciar.setForeground(new java.awt.Color(38, 85, 100));
        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18x18/Turn off.png"))); // NOI18N
        btnReiniciar.setText("  Reniciar");
        btnReiniciar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnReiniciar.setBorderPainted(false);
        btnReiniciar.setContentAreaFilled(false);
        btnReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReiniciar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReiniciar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReiniciar.setIconTextGap(1);
        btnReiniciar.setOpaque(true);
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        lblServidor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblServidor.setForeground(new java.awt.Color(51, 51, 51));
        lblServidor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServidor.setText("Servidor");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24x24/Table.png"))); // NOI18N
        btnProduto.setText("Produtos");
        btnProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto.setIconTextGap(1);
        btnProduto.setInheritsPopupMenu(true);
        btnProduto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(btnProduto);

        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24x24/Shopping cart.png"))); // NOI18N
        btnCompra.setText("Compras");
        btnCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompra.setIconTextGap(1);
        btnCompra.setInheritsPopupMenu(true);
        btnCompra.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });
        jPanel2.add(btnCompra);

        btnvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24x24/Mobile-phone.png"))); // NOI18N
        btnvenda.setText("Venda");
        btnvenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnvenda.setIconTextGap(1);
        btnvenda.setInheritsPopupMenu(true);
        btnvenda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnvenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvendaActionPerformed(evt);
            }
        });
        jPanel2.add(btnvenda);

        btnContaPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24x24/Next.png"))); // NOI18N
        btnContaPagar.setText("C. Pagar");
        btnContaPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContaPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContaPagar.setIconTextGap(1);
        btnContaPagar.setInheritsPopupMenu(true);
        btnContaPagar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnContaPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContaPagarActionPerformed(evt);
            }
        });
        jPanel2.add(btnContaPagar);

        btnContaReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24x24/Previous.png"))); // NOI18N
        btnContaReceber.setText("C. Receber");
        btnContaReceber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContaReceber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContaReceber.setIconTextGap(1);
        btnContaReceber.setInheritsPopupMenu(true);
        btnContaReceber.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnContaReceber.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContaReceberActionPerformed(evt);
            }
        });
        jPanel2.add(btnContaReceber);

        btnPlantio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24x24/Sync.png"))); // NOI18N
        btnPlantio.setText("Plantio");
        btnPlantio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlantio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlantio.setIconTextGap(1);
        btnPlantio.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnPlantio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlantio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantioActionPerformed(evt);
            }
        });
        jPanel2.add(btnPlantio);

        btnRequisicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24x24/How-to.png"))); // NOI18N
        btnRequisicao.setText("Requisição");
        btnRequisicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRequisicao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRequisicao.setIconTextGap(1);
        btnRequisicao.setInheritsPopupMenu(true);
        btnRequisicao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRequisicao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequisicaoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRequisicao);

        btnProducao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24x24/3d bar chart.png"))); // NOI18N
        btnProducao.setText("Produção");
        btnProducao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducao.setIconTextGap(1);
        btnProducao.setInheritsPopupMenu(true);
        btnProducao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnProducao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducaoActionPerformed(evt);
            }
        });
        jPanel2.add(btnProducao);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/fundoTransTelaLogin.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatahora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblDadosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(lblServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServidor)
                    .addComponent(btnReiniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDadosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDatahora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelDeTrabalho.setLayer(kGradientPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDeTrabalhoLayout = new javax.swing.GroupLayout(painelDeTrabalho);
        painelDeTrabalho.setLayout(painelDeTrabalhoLayout);
        painelDeTrabalhoLayout.setHorizontalGroup(
            painelDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelDeTrabalhoLayout.setVerticalGroup(
            painelDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDeTrabalho)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(painelDeTrabalho)
                .addGap(0, 0, 0))
        );

        barraMenu.setBackground(new java.awt.Color(84, 76, 76));
        barraMenu.setForeground(new java.awt.Color(255, 255, 255));
        barraMenu.setAutoscrolls(true);
        barraMenu.setMinimumSize(new java.awt.Dimension(80, 30));
        barraMenu.setOpaque(true);
        barraMenu.setPreferredSize(new java.awt.Dimension(577, 35));

        jMenu1.setBackground(new java.awt.Color(84, 76, 76));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18x18/Add.png"))); // NOI18N
        jMenu1.setText("Cadastros");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JItemMenu_Prod.setText("Produto");
        JItemMenu_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemMenu_ProdActionPerformed(evt);
            }
        });
        jMenu1.add(JItemMenu_Prod);

        JItemMenu_Cat.setText("Categoria");
        JItemMenu_Cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemMenu_CatActionPerformed(evt);
            }
        });
        jMenu1.add(JItemMenu_Cat);

        JItemMenu_Sub.setText("Sub Categoria");
        JItemMenu_Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemMenu_SubActionPerformed(evt);
            }
        });
        jMenu1.add(JItemMenu_Sub);

        JItemMenu_Forn.setText("Fornecedor");
        JItemMenu_Forn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemMenu_FornActionPerformed(evt);
            }
        });
        jMenu1.add(JItemMenu_Forn);

        JItemMenu_Cli.setText("Cliente");
        JItemMenu_Cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemMenu_CliActionPerformed(evt);
            }
        });
        jMenu1.add(JItemMenu_Cli);

        jMenuItem4.setText("Marca");
        jMenuItem4.setEnabled(false);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Fabricante");
        jMenuItem5.setEnabled(false);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        barraMenu.add(jMenu1);

        menuCompra.setBackground(new java.awt.Color(84, 76, 76));
        menuCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18x18/List.png"))); // NOI18N
        menuCompra.setText("Compras");
        menuCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        subMCompra.setText("Compras");
        subMCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMCompraActionPerformed(evt);
            }
        });
        menuCompra.add(subMCompra);

        subMSC.setText("Solicitação de Compra");
        subMSC.setEnabled(false);
        subMSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMSCActionPerformed(evt);
            }
        });
        menuCompra.add(subMSC);

        subMPC.setText("Pedido de Compra");
        subMPC.setEnabled(false);
        subMPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMPCActionPerformed(evt);
            }
        });
        menuCompra.add(subMPC);

        barraMenu.add(menuCompra);

        menuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18x18/Shopping cart.png"))); // NOI18N
        menuVenda.setText("Vendas");
        menuVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem6.setText("Vendas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuVenda.add(jMenuItem6);

        jMenuItem7.setText("Finalizar Venda");
        jMenuItem7.setEnabled(false);
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuVenda.add(jMenuItem7);

        jMenuItem8.setText("Orçamento");
        jMenuItem8.setEnabled(false);
        menuVenda.add(jMenuItem8);

        jMenuItem11.setText("Vendedores");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuVenda.add(jMenuItem11);

        barraMenu.add(menuVenda);

        menuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18x18/Dollar.png"))); // NOI18N
        menuFinanceiro.setText("Financeiro");
        menuFinanceiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem12.setText("Contas a Pagar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menuFinanceiro.add(jMenuItem12);

        jMenuItem13.setText("Contas a Receber");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menuFinanceiro.add(jMenuItem13);

        jMenuItem14.setText("Tesoraria");
        jMenuItem14.setEnabled(false);
        menuFinanceiro.add(jMenuItem14);

        jMenuItem15.setText("Fluxo de Caixa");
        jMenuItem15.setEnabled(false);
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        menuFinanceiro.add(jMenuItem15);

        jMenuItem25.setText("Caixa Diário");
        jMenuItem25.setEnabled(false);
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        menuFinanceiro.add(jMenuItem25);

        itemMenuBancos.setText("Bancos");
        itemMenuBancos.setEnabled(false);
        itemMenuBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuBancosActionPerformed(evt);
            }
        });
        menuFinanceiro.add(itemMenuBancos);

        jMenuItem24.setText("Caixinha");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        menuFinanceiro.add(jMenuItem24);

        barraMenu.add(menuFinanceiro);

        JmRH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18x18/Boss.png"))); // NOI18N
        JmRH.setText("Gestão de Pessoal");
        JmRH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem16.setText("Recusos Humanos");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        JmRH.add(jMenuItem16);

        jMenuItem1.setText("Segurança do Trabalho");
        JmRH.add(jMenuItem1);

        jMenuItem2.setText("Medicina do Trabalho");
        JmRH.add(jMenuItem2);

        barraMenu.add(JmRH);

        jMenuMovimentacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagens/Business.png"))); // NOI18N
        jMenuMovimentacao.setText("Movimentos Internos");

        jMenuItem21.setText("Requisição");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenuMovimentacao.add(jMenuItem21);

        jMenuItem34.setText("Plantio");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenuMovimentacao.add(jMenuItem34);

        jMenuItem35.setText("Produção");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenuMovimentacao.add(jMenuItem35);

        barraMenu.add(jMenuMovimentacao);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18x18/Abort.png"))); // NOI18N
        jMenu8.setText("Sobre");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        barraMenu.add(jMenu8);

        JmEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18x18/3d bar chart.png"))); // NOI18N
        JmEstoque.setText("Estoque");
        JmEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem17.setText("Saldo Inicial");
        jMenuItem17.setEnabled(false);
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        JmEstoque.add(jMenuItem17);

        jMenuItem18.setText("Saldo Atual");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        JmEstoque.add(jMenuItem18);

        jMenuItem19.setText("Inventario");
        jMenuItem19.setEnabled(false);
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        JmEstoque.add(jMenuItem19);

        jMenuItem20.setText("Fechar Periodo");
        jMenuItem20.setEnabled(false);
        JmEstoque.add(jMenuItem20);

        jMenuItem9.setText("Kardex");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        JmEstoque.add(jMenuItem9);

        barraMenu.add(JmEstoque);

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18x18/User group.png"))); // NOI18N
        menuUsuario.setText("Usuario");
        menuUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuNovoUsuario.setText("Cadastro de Usuario");
        menuNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuNovoUsuario);

        jMenuItem26.setText("Alterar Senha");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem26);

        barraMenu.add(menuUsuario);

        menuPermissoes.setText("Gerenciar Permissões");
        menuPermissoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPermissoes.setOpaque(true);

        jMenu14.setText("Financeiro");

        jMenuItem32.setText("Contas a Pagar");
        jMenu14.add(jMenuItem32);

        jMenuItem33.setText("Contas Receber");
        jMenu14.add(jMenuItem33);

        menuPermissoes.add(jMenu14);

        jMenu12.setText("Atualizações Gerais");

        jMenu13.setText("Produtos");

        jMenuItem28.setText("Produto");
        jMenu13.add(jMenuItem28);

        jMenuItem29.setText("Categorias");
        jMenu13.add(jMenuItem29);

        jMenuItem30.setText("Sub Categoria");
        jMenu13.add(jMenuItem30);

        jMenuItem31.setText("Unidade de Medida");
        jMenu13.add(jMenuItem31);

        jMenuItem36.setText("Marcas");
        jMenu13.add(jMenuItem36);

        jMenuItem37.setText("Fabricantes");
        jMenu13.add(jMenuItem37);

        jMenu12.add(jMenu13);

        menuPermissoes.add(jMenu12);

        barraMenu.add(menuPermissoes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        JD_SOBRE sobre = new JD_SOBRE(this, true);
        sobre.setVisible(true);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        ESTOQUE estoque = new ESTOQUE();
        estoque.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void JItemMenu_FornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemMenu_FornActionPerformed
        BASE_FORNECEDOR fornecedor = new BASE_FORNECEDOR();
        fornecedor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JItemMenu_FornActionPerformed

    private void JItemMenu_SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemMenu_SubActionPerformed
        BASE_SUB_CATEGORIA subCategoria = new BASE_SUB_CATEGORIA();
        subCategoria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JItemMenu_SubActionPerformed

    private void JItemMenu_CatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemMenu_CatActionPerformed
        BASE_CATEGORIA categoria = new BASE_CATEGORIA();
        categoria.setVisible(true);
        dispose();
    }//GEN-LAST:event_JItemMenu_CatActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        BASE_MARCAS marca = new BASE_MARCAS();
        marca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void JItemMenu_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemMenu_ProdActionPerformed
        BASE_PROD produto = new BASE_PROD();
        produto.carregaArray();
        produto.carregaTabela();
        produto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JItemMenu_ProdActionPerformed

    private void JItemMenu_CliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemMenu_CliActionPerformed
        BASE_CLIENTE cliente = new BASE_CLIENTE();
        cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JItemMenu_CliActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        BASE_FABRICANTES fabricante = new BASE_FABRICANTES();
        fabricante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void subMCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMCompraActionPerformed
        BASE_COMPRA compra = new BASE_COMPRA();
        compra.carregaTabela();
        compra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_subMCompraActionPerformed

    private void subMPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMPCActionPerformed

    private void subMSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMSCActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        BROWSER_VENDAS vendas = new BROWSER_VENDAS();
        vendas.carregaTabela();
        vendas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        ModelOperacaoCaixaPDV modCaixa = new ModelOperacaoCaixaPDV();
        modCaixa.setOperacao("ACESSAR CAIXA");
        Aprovador_Caixa_PDV aprovador = new Aprovador_Caixa_PDV(this, true);
        aprovador.setVisible(true);


    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        BASE_CONTA_PAGAR conta = new BASE_CONTA_PAGAR();
        conta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JD_MOV_ESTOQUE kardex = new JD_MOV_ESTOQUE(this, true);
        kardex.setVisible(true);

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        ALTERAR_SENHA alterarSenha = new ALTERAR_SENHA(this, true);
        alterarSenha.setVisible(true);

    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        BASE_CONTA_RECEBER base = new BASE_CONTA_RECEBER();
        base.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed


    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed

        JD_DIG_INV invet = new JD_DIG_INV(this, true);
        invet.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        this.dispose();
        DJ_SERVIDOR server = new DJ_SERVIDOR(new javax.swing.JFrame(), true);
        server.setVisible(true);


    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        JD_VENDEDORES vend = new JD_VENDEDORES(this, true);
        vend.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        BROWSER_RH funcionarios = new BROWSER_RH();
        funcionarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void itemMenuBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuBancosActionPerformed
        BASE_BANCOS banco = new BASE_BANCOS();
        banco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemMenuBancosActionPerformed

    private void menuNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNovoUsuarioActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        BASE_REQ1 req = new BASE_REQ1();
        req.carregaTabela();
        req.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        BASE_PLANTIO plantio = new BASE_PLANTIO();
        plantio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        BASE_PRODUCAO produ = new BASE_PRODUCAO();
        produ.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        BASE_CAIXA caixinha = new BASE_CAIXA();
        caixinha.setVisible(true);
        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void btnPlantioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantioActionPerformed

        BASE_PLANTIO plantio = new BASE_PLANTIO();
        plantio.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnPlantioActionPerformed

    private void btnRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequisicaoActionPerformed
        BASE_REQ1 req = new BASE_REQ1();
        req.carregaTabela();
        req.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRequisicaoActionPerformed

    private void btnProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducaoActionPerformed
        BASE_PRODUCAO produ = new BASE_PRODUCAO();
        produ.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProducaoActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        BASE_PROD produto = new BASE_PROD();
        produto.carregaArray();
        produto.carregaTabela();
        produto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnContaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContaPagarActionPerformed
        BASE_CONTA_PAGAR conta = new BASE_CONTA_PAGAR();
        conta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContaPagarActionPerformed

    private void btnContaReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContaReceberActionPerformed
        BASE_CONTA_RECEBER base = new BASE_CONTA_RECEBER();
        base.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContaReceberActionPerformed

    private void btnvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvendaActionPerformed
        BROWSER_VENDAS vendas = new BROWSER_VENDAS();
        vendas.carregaTabela();
        vendas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvendaActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        BASE_COMPRA compra = new BASE_COMPRA();
        compra.carregaTabela();
        compra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCompraActionPerformed
    public void centerWindow(Component frame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = frame.getSize();
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        frame.setLocation((screenSize.width - frameSize.width) >> 1, (screenSize.height - frameSize.height) >> 1);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JItemMenu_Cat;
    private javax.swing.JMenuItem JItemMenu_Cli;
    private javax.swing.JMenuItem JItemMenu_Forn;
    private javax.swing.JMenuItem JItemMenu_Prod;
    private javax.swing.JMenuItem JItemMenu_Sub;
    private javax.swing.JMenu JmEstoque;
    private javax.swing.JMenu JmRH;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnContaPagar;
    private javax.swing.JButton btnContaReceber;
    private javax.swing.JButton btnPlantio;
    private javax.swing.JButton btnProducao;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnRequisicao;
    private javax.swing.JButton btnvenda;
    private javax.swing.JMenuItem itemMenuBancos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuMovimentacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblDadosEmpresa;
    private javax.swing.JLabel lblDatahora;
    private javax.swing.JLabel lblServidor;
    private javax.swing.JMenu menuCompra;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenuItem menuNovoUsuario;
    private javax.swing.JMenu menuPermissoes;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JDesktopPane painelDeTrabalho;
    private javax.swing.JMenuItem subMCompra;
    private javax.swing.JMenuItem subMPC;
    private javax.swing.JMenuItem subMSC;
    // End of variables declaration//GEN-END:variables

}
