/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author claudinei
 */
public class modelo extends javax.swing.JFrame {

    /**
     * Creates new form modelo
     */
    public modelo() {
        initComponents();
        centerWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelDeTrabalho = new javax.swing.JDesktopPane(){

        };
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        lblContaPagar = new javax.swing.JLabel();
        lblContaReceber = new javax.swing.JLabel();
        lblPedido = new javax.swing.JLabel();
        lblVenda = new javax.swing.JLabel();
        lblCompra = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        lblDatahora = new javax.swing.JLabel();
        lblDadosEmpresa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        lblServidor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        painelDeTrabalho.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));

        kGradientPanel2.setkEndColor(new java.awt.Color(94, 110, 110));
        kGradientPanel2.setkGradientFocus(1500);
        kGradientPanel2.setkStartColor(new java.awt.Color(94, 110, 110));

        lblContaPagar.setBackground(new java.awt.Color(94, 110, 110));
        lblContaPagar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblContaPagar.setForeground(new java.awt.Color(255, 255, 255));
        lblContaPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContaPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.png"))); // NOI18N
        lblContaPagar.setText("C. Pagar");
        lblContaPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContaPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblContaPagar.setOpaque(true);
        lblContaPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblContaPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContaPagarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContaPagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContaPagarMouseExited(evt);
            }
        });

        lblContaReceber.setBackground(new java.awt.Color(94, 110, 110));
        lblContaReceber.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblContaReceber.setForeground(new java.awt.Color(255, 255, 255));
        lblContaReceber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContaReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        lblContaReceber.setText("C. Receber");
        lblContaReceber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContaReceber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblContaReceber.setOpaque(true);
        lblContaReceber.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblContaReceber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContaReceberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContaReceberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContaReceberMouseExited(evt);
            }
        });

        lblPedido.setBackground(new java.awt.Color(94, 110, 110));
        lblPedido.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/3.png"))); // NOI18N
        lblPedido.setText("Pedido");
        lblPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPedido.setOpaque(true);
        lblPedido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPedidoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPedidoMouseExited(evt);
            }
        });

        lblVenda.setBackground(new java.awt.Color(94, 110, 110));
        lblVenda.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblVenda.setForeground(new java.awt.Color(255, 255, 255));
        lblVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/4.png"))); // NOI18N
        lblVenda.setText("Venda");
        lblVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVenda.setOpaque(true);
        lblVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVendaMouseExited(evt);
            }
        });

        lblCompra.setBackground(new java.awt.Color(94, 110, 110));
        lblCompra.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/5.png"))); // NOI18N
        lblCompra.setText("Compra");
        lblCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCompra.setOpaque(true);
        lblCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCompraMouseExited(evt);
            }
        });

        lblProduto.setBackground(new java.awt.Color(94, 110, 110));
        lblProduto.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.png"))); // NOI18N
        lblProduto.setText("Produto");
        lblProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProduto.setOpaque(true);
        lblProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProdutoMouseExited(evt);
            }
        });

        lblDatahora.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblDatahora.setForeground(new java.awt.Color(204, 204, 204));
        lblDatahora.setText("Data e Hora:");

        lblDadosEmpresa.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblDadosEmpresa.setForeground(new java.awt.Color(204, 204, 204));
        lblDadosEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDadosEmpresa.setText(" Direitos de uso temporário cedido à: BIG JOY BRINQUEDOS | Modulo: TESTE");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/LogoMenu.png"))); // NOI18N

        btnReiniciar.setBackground(new java.awt.Color(102, 102, 102));
        btnReiniciar.setForeground(new java.awt.Color(204, 204, 204));
        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/Reiniciar.png"))); // NOI18N
        btnReiniciar.setText("Reniciar");
        btnReiniciar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnReiniciar.setBorderPainted(false);
        btnReiniciar.setContentAreaFilled(false);
        btnReiniciar.setOpaque(true);
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        lblServidor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblServidor.setForeground(new java.awt.Color(255, 255, 255));
        lblServidor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServidor.setText("Servidor");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDadosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(lblDatahora, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblContaReceber)
                                            .addComponent(lblPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblContaPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblContaReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblContaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDadosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDatahora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelDeTrabalho.setLayer(kGradientPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDeTrabalhoLayout = new javax.swing.GroupLayout(painelDeTrabalho);
        painelDeTrabalho.setLayout(painelDeTrabalhoLayout);
        painelDeTrabalhoLayout.setHorizontalGroup(
            painelDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelDeTrabalhoLayout.setVerticalGroup(
            painelDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDeTrabalho)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(painelDeTrabalho)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblContaPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContaPagarMouseClicked
        BASE_CONTA_PAGAR pagar = new BASE_CONTA_PAGAR();
        pagar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblContaPagarMouseClicked

    private void lblContaPagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContaPagarMouseEntered
        lblContaPagar.setBackground(new java.awt.Color(94, 100, 100));
    }//GEN-LAST:event_lblContaPagarMouseEntered

    private void lblContaPagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContaPagarMouseExited
        lblContaPagar.setBackground(new java.awt.Color(94, 110, 110));//
    }//GEN-LAST:event_lblContaPagarMouseExited

    private void lblContaReceberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContaReceberMouseClicked
        BASE_CONTA_RECEBER base = new BASE_CONTA_RECEBER();
        base.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblContaReceberMouseClicked

    private void lblContaReceberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContaReceberMouseEntered
        lblContaReceber.setBackground(new java.awt.Color(94, 100, 100));
    }//GEN-LAST:event_lblContaReceberMouseEntered

    private void lblContaReceberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContaReceberMouseExited
        lblContaReceber.setBackground(new java.awt.Color(94, 110, 110));//
    }//GEN-LAST:event_lblContaReceberMouseExited

    private void lblPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPedidoMouseClicked

    private void lblPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidoMouseEntered
        lblPedido.setBackground(new java.awt.Color(94, 100, 100));
    }//GEN-LAST:event_lblPedidoMouseEntered

    private void lblPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidoMouseExited
        lblPedido.setBackground(new java.awt.Color(94, 110, 110));//
    }//GEN-LAST:event_lblPedidoMouseExited

    private void lblVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendaMouseClicked
        BROWSER_VENDAS venda = new BROWSER_VENDAS();
        venda.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVendaMouseClicked

    private void lblVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendaMouseEntered
        lblVenda.setBackground(new java.awt.Color(94, 100, 100));
    }//GEN-LAST:event_lblVendaMouseEntered

    private void lblVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendaMouseExited
        lblVenda.setBackground(new java.awt.Color(94, 110, 110));//
    }//GEN-LAST:event_lblVendaMouseExited

    private void lblCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCompraMouseClicked
        BASE_COMPRA compra = new BASE_COMPRA();

        compra.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCompraMouseClicked

    private void lblCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCompraMouseEntered
        lblCompra.setBackground(new java.awt.Color(94, 100, 100));
    }//GEN-LAST:event_lblCompraMouseEntered

    private void lblCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCompraMouseExited
        lblCompra.setBackground(new java.awt.Color(94, 110, 110));//
    }//GEN-LAST:event_lblCompraMouseExited

    private void lblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutoMouseClicked
        BASE_PROD produto = new BASE_PROD();
        //  produto.carregaTabela();
        // produto.carregaArray();
        //  produto.carregaTabela();
        produto.setVisible(true);

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblProdutoMouseClicked

    private void lblProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutoMouseEntered
        lblProduto.setBackground(new java.awt.Color(94, 100, 100));
    }//GEN-LAST:event_lblProdutoMouseEntered

    private void lblProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutoMouseExited
        lblProduto.setBackground(new Color(94, 110, 110));
    }//GEN-LAST:event_lblProdutoMouseExited

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        this.dispose();
        DJ_SERVIDOR server = new DJ_SERVIDOR(new javax.swing.JFrame(), true);
        server.setVisible(true);

    }//GEN-LAST:event_btnReiniciarActionPerformed

    public void centerWindow(Component frame)  
    {  
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
        Dimension frameSize = frame.getSize();  
        if ( frameSize.width > screenSize.width )  
            frameSize.width = screenSize.width;  
                 if ( frameSize.height > screenSize.height )  
            frameSize.height = screenSize.height;  
                  frame.setLocation ( (screenSize.width - frameSize.width ) >> 1, (screenSize.height - frameSize.height) >> 1 );  
    } 

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblCompra;
    private javax.swing.JLabel lblContaPagar;
    private javax.swing.JLabel lblContaReceber;
    private javax.swing.JLabel lblDadosEmpresa;
    private javax.swing.JLabel lblDatahora;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblServidor;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JDesktopPane painelDeTrabalho;
    // End of variables declaration//GEN-END:variables
}
